pipeline{

    agent any 

    tools {
      maven 'my-maven'
     }

    stages{
        stage('build'){
           steps{
              sh 'mvn clean package'
           }

           post{
            success{
                archiveArtifacts artifacts : '**/target/*.war'
            }
           }
        }
    
    }
}